version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:1.11.2
    container_name: selenoid
    network_mode: selenoid
    ports:
      - 4445:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/it/browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid -limit 12
    restart: unless-stopped

  selenoid1:
    image: aerokube/selenoid:1.11.2
    container_name: selenoid1
    network_mode: selenoid1
    ports:
      - 4446:4444
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/it/browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid1 -limit 12
    restart: unless-stopped

  ggr:
    image: aerokube/ggr:1.7.2
    container_name: ggr
    ports:
      - 4444:4444
    volumes:
      - /etc/grid-router/:/etc/grid-router:ro
    command: -guests-allowed -guests-quota "it" -verbose -quotaDir /etc/grid-router/quota
    restart: unless-stopped

  ggr-ui:
    image: aerokube/ggr-ui:1.2.0
    container_name: ggr-ui
    ports:
      - 8888:8888
    volumes:
      - /etc/grid-router/quota/:/etc/grid-router/quota:ro
    restart: unless-stopped

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid-ui
    ports:
      - 8080:8080
    command: --selenoid-uri http://172.17.0.1:8888
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    network_mode: host
    volumes:
      - /home/it/nginx/:/etc/nginx/conf.d:ro
    restart: unless-stopped

networks:
  selenoid:
    external: true
  selenoid1:
    external: true