version: '3.8'

services:
  selenoid1:
    image: aerokube/selenoid:1.11.2
    container_name: selenoid1
    ports:
      - "4445:4444"
    networks:
      - selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid -limit 12
    depends_on:
      - chrome
    restart: always

  selenoid2:
    image: aerokube/selenoid:1.11.2
    container_name: selenoid2
    ports:
      - "4446:4444"
    networks:
      - selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid -limit 12
    depends_on:
      - chrome
    restart: always

  chrome:
    image: selenoid/chrome:121.0
    networks:
      - selenoid
    command: []

  ggr:
    image: aerokube/ggr:1.7.2
    container_name: ggr
    ports:
      - "4444:4444"
    networks:
      - selenoid
    volumes:
      - /etc/grid-router/:/etc/grid-router:ro
    command: >
      -guests-allowed
      -guests-quota ggr-it-user
      -verbose
      -quotaDir /etc/grid-router/quota
    depends_on:
      - selenoid1
      - selenoid2
    restart: always

  ggr-ui:
    image: aerokube/ggr-ui:1.2.0
    container_name: ggr-ui
    ports:
      - "8888:8888"
    networks:
      - selenoid
    volumes:
      - /etc/grid-router/quota/:/etc/grid-router/quota:ro
    depends_on:
      - ggr
    restart: always

  selenoid-ui:
    image: aerokube/selenoid-ui:1.10.11
    container_name: selenoid-ui
    ports:
      - "8080:8080"
    networks:
      - selenoid
    command: --selenoid-uri http://172.18.0.6:8888
    depends_on:
      - ggr-ui
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "90:90"
    networks:
      - selenoid
    volumes:
      - /home/it/nginx/selenoid.conf:/etc/nginx/conf.d/selenoid.conf:ro
    depends_on:
      - selenoid-ui
      - ggr
    restart: always

networks:
  selenoid1:
    driver: bridge

volumes:
  browsers:
    driver: local