version: '3.8'

services:
  selenoid:
    image: aerokube/selenoid:1.11.2
    container_name: selenoid
    ports:
      - "4445:4444"
    networks:
      - selenoid
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./browsers.json:/etc/selenoid/browsers.json:ro
    command: -container-network=selenoid -limit 12
    depends_on:
      - chrome
    restart: always

  chrome:
    image: selenoid/chrome:121.0
    networks:
      - selenoid
    command: []

networks:
  selenoid:
    driver: bridge

volumes:
  browsers:
    driver: local